sensorbee/sensorbee

cmd/build_sensorbee/main.go

If we don't download SensorBee itself, then we may get errors about missing dependencies when executing `build_sensorbee` if some SensorBee components are neither mentioned in `build.yaml` nor required by `build_sensorbee`, but required to compile a `sensorbee` executable.

also refresh SensorBee itself when executing build_sensorbee

---

cmd/build_sensorbee/main.go
cmd/lib/exp/clean.go
cmd/lib/exp/file.go
cmd/lib/exp/run.go
cmd/lib/run/cmd.go
cmd/lib/runfile/cmd.go
cmd/lib/shell/cmd_line_tool.go
cmd/lib/shell/controller.go
cmd/lib/topology/cmd.go
cmd/lib/topology/cmd_test.go
cmd/lib/topology/create.go
cmd/lib/topology/drop.go
cmd/lib/topology/list.go
cmd/sensorbee/default_main.go

This commit also changes some actions not to use panic/recover for termination processing.
fixes #60 
After merging this PR, we need to bump the version to 0.4.2. At that time, we should resolve the issue #13 and stop hardcoding the version number in build_sensorbee/main.go.

Support cli.ActionFunc to suppress cli's DEPRECATED message

---

cmd/lib/runfile/cmd.go

I fixed the code to trim leading/trailing spaces of names.
fixes #22

Trim names of UDSs given by --save-uds

---

cmd/bql/bql_main.go
cmd/lib/shell/cmd_line_tool.go

refs #55 
```
$ cd /path/to/sensorbee/cmd/bql
$ go install
```
then
```
$ bql -t test
test>
```

add bql command, same function as "sensorbee shell"

---

.travis.yml

sensorbee needs to be placed under gopkg.in/sensorbee/sensorbee.v0. However, it's currently copied at github.com/sensorbee/sensorbee and all tests have not been actually working properly.
https://github.com/kothar/brotli-go/pull/18 was very helpful.

Fix .travis.yml for gopkg.in

---

core/default_box_node.go

`StopOnDisconnect` wasn't able to stop when the argument is `Inbound | Outbound` and there's no outbound connection.
fix #34

Fix defaultBoxNode.StopOnDisconnect to handle Outbound correctly

---

bql/builtin.go
bql/builtin_test.go

I added two new parameters to `file` source: `repeat` and `interval`.
`repeat` has similar functionality to `loop` proposed in #29. Instead of choosing looping forever or not, `repeat` parameter allows a source to be rewound for the specified number of times. If the value is negative, it acts just like `loop = true`.
`interval` parameter has the same implementation as `node_statuses` source.
fixes #29

Add new parameters to the built-in file source

---

bql/topology_builder.go
core/default_box_node.go
core/default_sink_node.go
core/node.go
core/node_test.go

I moved `MaxBufferSize` to `core` package and changed its name to `MaxCapacity` to be consistent in `core` package. It'd probably be better to rename `Capacity` in `core` package to `BufferSize`, but I wasn't sure enough and just moved the constant in this PR.
fixes #37

Move buffer size check to core package from bql

---

server/topologies.go

I found the case that receive returns an error but send succeeds. I'm not sure how it was caused, but it produced a lot of logs saying `err=EOF`. So, I added EOF check.

Check EOF on the first read in the WebSocket loop

---

server/topologies.go

I added access logging. Payloads should probably be included but I didn't do it for the moment.

Add access logging of request sent through WebSocket

---

bql/topology_builder.go

When streaming video frames from RPi, the process is easily killed by OOM if the receiver can't consume tuples fast enough. Although users can specify `BUFFER SIZE` and `DROP IF` in the SELECT statement, there's no way to specify those parameters for the Sink connected to the SELECT BQL box.
This problem should be solved by adding a way in SELECT (and perhaps INSERT INTO) statements to specify buffer size and drop mode, but it's temporarily fixed by setting 1 to the buffer size (i.e. capacity).

Set the capacity of the SELECT sink to 1 temporarily

---

bql/udf/builtin/conversion.go
bql/udf/builtin/conversion_test.go
bql/udf/builtin/init.go

I added blob_to_raw_string UDF. This UDF is used when a user wants to convert a blob to a string without using base64 encoding. Because it's invalid for a string to have non UTF-8 characters, this function validates the given data.Blob before converting it to data.String.

Add blob_to_raw_string built-in UDF

---

bql/udf/builtin/string.go
bql/udf/builtin/string_test.go
data/array.go
data/map.go
data/value.go

`data.NewValue` now supports `json.Number`. Also, `data.Array` and `data.Map` parse JSON with `json.Decoder.UseNumber` enabled.
fixes #106

Support json.Number in data package

---

bql/udf/generic_func_test.go
data/type_conversions.go
data/type_conversions_test.go

I added `Array` -> `Blob` conversion when the array only contains uint8 values.

Add Array to Blob conversion when an array contains uint8 values

---

cmd/lib/runfile/cmd.go
core/context.go
core/dropped_tuple_collector_source_test.go
core/pipe.go
server/config/config_test.go
server/config/logging.go
server/config/logging_test.go
server/context.go
server/topologies.go

I added a new option: `log_destinationless_tuples`. A destinationless tuple is a kind of dropped tuples. It's dropped when a source or a stream doesn't have any destination. To enable destinationless tuple logging, both `log_destinationless_tuples` and `log_dropped_tuples` options need to be true. Only enabling `log_dropped_tuples` doesn't report destinationless tuples.
This is a breaking change but destinationless tuples will not be reported by default.
fixes #125

Add log_destinationless_tuples option

---

cmd/lib/topology/cmd_test.go

`cli.HandleExitError` currently always calls `os.Exit` that causes test failures. I added a workaround for it.
See https://github.com/urfave/cli/issues/565

Add workaround for cli.HandleExitError in tests

---

cmd/build_sensorbee/main.go
cmd/build_sensorbee/main_test.go

I removed unofficial and experimental `exp` commands from the default command list of `build_sensorbee` to avoid confusion.

Remove exp command from default subcommands

---

core/pipe.go
core/pipe_test.go

In `dataSources` in pipe.go, fatal and temporary errors were correctly counted, but normal errors were not.

Fix dataSources to count normal errors

---

bql/builtin.go
bql/builtin_test.go

- use `data.Decoder` on file sink and file source
- support file rotation option on file sink, using lumberjack which has already used on server/log.

Support file rotation option on file sink

---

data/array.go

Provide Array.Copy to create deep copies of Array

---

.travis.yml

From next version, SensorBee only supports Go 1.8 or later.
fixes #119

Only Support Go 1.8 or later

---

bql/bql_box.go
cmd/lib/runfile/cmd.go
core/context.go
core/node.go
server/context.go
server/topologies.go

Hi.
This PR syncs @sirupsen lowercasing his logrus repository name which is now
`https://github.com/sirupsen/logrus`
> Seeing weird case-sensitive problems? It's in the past been possible to import Logrus as both upper- and lower-case. Due to the Go package environment, this caused issues in the community and we needed a standard. Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.

Lowercased logrus repository dep

---

bql/topology_builder.go
bql/topology_builder_test.go

This PR still has a problem that a user can create reproduce the issue using a UDSF. However, I think this is sufficient for now.
fixes #154

Fix TopologyBuilder to reject streams containing a selfloop
